{% set name = "peakutils" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ff2e7f3330b93024fe8da1ee04e00389e26bcb2ef79bd2f9cf86ccd4962e114

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - peakutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/lucashnegri/peakutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Peak detection utilities for 1D data

  description: |
    This package provides utilities related to the detection of peaks on 
    1D data. Includes functions to estimate baselines, finding the 
    indexes of peaks in the data and performing Gaussian fitting or centroid 
    computation to further increase the resolution of the peak detection.
  doc_url: http://pythonhosted.org/PeakUtils/
  dev_url: https://bitbucket.org/lucashnegri/peakutils/

extra:
  recipe-maintainers:
    - pgunn
    - xmnlab
