travis:
  secure:
    BINSTAR_TOKEN: sPyc4natYmxCiblmZynMi4y5xkuS7uVCdEeCmgTLa7EJdW8gKzasrtbothrS7y+7NM/FpVwy0RUANDqJNIkfBGEgMNYx/9zi861T2y8XYRW9bOOP7tenuZ5E5xZbbGCtuYS/gqZ+z7MC7XWkXPPhHv1TP1wCMUWQTB1I33jrFMe809/Yu1yv9q0Bnk3CKLiHvA8L+R3f0yGXDHzVJAl5EvqgL3r+T2+K13hy2BXsaoORcZUfW25SgoBPwktodhiAgS0j48VvyTFhR2fOU0bcCRth8FQeI6968k2dvZb+ebuaVhIHJ/soLdQzrnoZQAc+0cs+SocIBAZRrvf4wPIP1vF6bfCxZhXZuEIlym9XIuGhTipl+NkQYE5MN+135zCmGjzTDAnXO5MPB/XVROGdhun8Hu97sOGmBIBxTGoTmgfdrBkIhhNmlquqGZxv+mlpkRaKabj0xjjNloA3CGgo61Y+F8/kZ2yWukkiiH8C6z2hyfBdV7O2BusfRkx5iJgtKZYPepasLpXRQsTJIF/9MkFJzfIW0OxujbnJ8LHNXEmszYasj5SfNdaw1TRyeBgqi5SuygV8ffD6705+ozebd9u8GBtVUeO8NYcOSQw6P0Xnuagvle9RJrADs7WRf3v0ZnPfWoXbi4w2r7ng9ojZZt5CECOqu+FGMwD9pWY4RZ8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
